/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.base.Predicates;
import com.google.common.collect.Collections2;
import com.google.common.collect.Lists;

import java.util.*;


/**
 * To start the application:
 * ./gradlew build
 * java -jar ./L01-gradle/build/libs/gradleHelloWorld-0.1.jar
 * <p>
 * To unzip the jar:
 * unzip -l L01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 */
public class HelloOtus {
    public static void main(String... args) {
        Object[] filteredVegetables = (Collections2.filter(Lists.newArrayList("carrot", "broccoli", "corn", "asparagus"), Predicates.containsPattern("c"))).toArray();
        Arrays.sort(filteredVegetables);
        for (Object item : filteredVegetables) {
            System.out.println(item);
        }
    }
}
